package misa.masterchild.model;

public class OrderDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.orderId
     *
     * @mbg.generated
     */
    private Integer orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.details
     *
     * @mbg.generated
     */
    private String details;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.quantity
     *
     * @mbg.generated
     */
    private Integer quantity;

    private OrderDetail(Builder builder) {
        setId(builder.id);
        setOrderid(builder.orderid);
        setDetails(builder.details);
        setQuantity(builder.quantity);
    }

    public static Builder newBuilder() {
        return new Builder();
    }

    public static Builder newBuilder(OrderDetail copy) {
        Builder builder = new Builder();
        builder.id = copy.id;
        builder.orderid = copy.orderid;
        builder.details = copy.details;
        builder.quantity = copy.quantity;
        return builder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.id
     *
     * @return the value of orderdetail.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.id
     *
     * @param id the value for orderdetail.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.orderId
     *
     * @return the value of orderdetail.orderId
     *
     * @mbg.generated
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.orderId
     *
     * @param orderid the value for orderdetail.orderId
     *
     * @mbg.generated
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.details
     *
     * @return the value of orderdetail.details
     *
     * @mbg.generated
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.details
     *
     * @param details the value for orderdetail.details
     *
     * @mbg.generated
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.quantity
     *
     * @return the value of orderdetail.quantity
     *
     * @mbg.generated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.quantity
     *
     * @param quantity the value for orderdetail.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public static final class Builder {
        private Integer id;
        private Integer orderid;
        private String details;
        private Integer quantity;

        private Builder() {
        }

        public Builder withId(Integer val) {
            id = val;
            return this;
        }

        public Builder withOrderid(Integer val) {
            orderid = val;
            return this;
        }

        public Builder withDetails(String val) {
            details = val;
            return this;
        }

        public Builder withQuantity(Integer val) {
            quantity = val;
            return this;
        }

        public OrderDetail build() {
            return new OrderDetail(this);
        }
    }
}