package misa.masterchild.model;

import java.util.Date;


public class Order {

    public Order() {
        super();
    }

    public Order(Integer id, String customername, Boolean status, Date orderdate, Date updated) {
        this();
        this.id = id;
        this.customername = customername;
        this.status = status;
        this.orderdate = orderdate;
        this.updated = updated;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.customerName
     *
     * @mbg.generated
     */
    private String customername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.orderDate
     *
     * @mbg.generated
     */
    private Date orderdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.updated
     *
     * @mbg.generated
     */
    private Date updated;

    private Order(Builder builder) {
        setStatus(builder.status);
        setId(builder.id);
        setCustomername(builder.customername);
    }

    public static Builder newBuilder() {
        return new Builder();
    }

    public static Builder newBuilder(Order copy) {
        Builder builder = new Builder();
        builder.status = copy.status;
        builder.id = copy.id;
        builder.customername = copy.customername;
        return builder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.customerName
     *
     * @return the value of order.customerName
     *
     * @mbg.generated
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.customerName
     *
     * @param customername the value for order.customerName
     *
     * @mbg.generated
     */
    public void setCustomername(String customername) {
        this.customername = customername == null ? null : customername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.status
     *
     * @return the value of order.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.status
     *
     * @param status the value for order.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.orderDate
     *
     * @return the value of order.orderDate
     *
     * @mbg.generated
     */
    public Date getOrderdate() {
        return orderdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.updated
     *
     * @return the value of order.updated
     *
     * @mbg.generated
     */
    public Date getUpdated() {
        return updated;
    }

    public static final class Builder {
        private Boolean status;
        private Integer id;
        private String customername;

        private Builder() {
        }

        public Builder withStatus(Boolean val) {
            status = val;
            return this;
        }

        public Builder withId(Integer val) {
            id = val;
            return this;
        }

        public Builder withCustomername(String val) {
            customername = val;
            return this;
        }

        public Order build() {
            return new Order(this);
        }
    }
}